---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      vmSize: ${AZURE_NODE_MACHINE_TYPE}
      osDisk:
        osType: "Linux"
        diskSizeGB: 128
      sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      preKubeadmCommands:
      - sed -i 's/\[plugins\]/[plugins]\\\n  [plugins.\\\""io.containerd.grpc.v1.cri\\\"".containerd.runtimes.wasm]\\\n  runtime_type = \\\""io.containerd.spin.v1\\\""/' /etc/containerd/config.toml
      - curl -o /tmp/containerd-shim-wasmserver-v1-${RUNWASI_VERSION:=v0.1.0}-linux-amd64.tar.gz -sLJO https://github.com/Mossaka/containerd-wasm-shims/releases/download/${RUNWASI_VERSION:=v0.1.0}/containerd-shim-wasmserver-v1-${RUNWASI_VERSION:=v0.1.0}-linux-amd64.tar.gz
      - sudo tar -xf /tmp/containerd-shim-wasmserver-v1-${RUNWASI_VERSION:=v0.1.0}-linux-amd64.tar.gz -C /usr/local/bin/
      - sudo service containerd restart
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data["local_hostname"] }}'
          kubeletExtraArgs:
            cloud-provider: azure
            cloud-config: /etc/kubernetes/azure.json
            azure-container-registry-config: /etc/kubernetes/azure.json
      files:
      - contentFrom:
          secret:
            name: ${CLUSTER_NAME}-md-0-azure-json
            key: worker-node-azure.json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
